// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AIStoryBuilders.Models;

public partial class CharacterCharacterBackgroundParagraph
{
    public int Id { get; set; }

    public int CharacterId { get; set; }

    public int CharacterBackgroundParagraphId { get; set; }

    public virtual Character Character { get; set; }

    public virtual CharacterBackgroundParagraph CharacterBackgroundParagraph { get; set; }
}