// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AIStoryBuilders.Models;

public partial class CharacterBackgroundVectorData
{
    public int Id { get; set; }

    public int CharacterBackgroundId { get; set; }

    public int VectorValueId { get; set; }

    public double VectorValue { get; set; }

    public virtual CharacterBackground CharacterBackground { get; set; }
}