// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AIStoryBuilders.Models;

public partial class CharacterBackground
{
    public int Id { get; set; }

    public int CharacterId { get; set; }

    public int Sequence { get; set; }

    public string Type { get; set; }

    public string Description { get; set; }

    public string ParagraphContent { get; set; }

    public int? TimelineId { get; set; }

    public virtual Character Character { get; set; }

    public virtual ICollection<CharacterBackgroundVectorData> CharacterBackgroundVectorData { get; set; } = new List<CharacterBackgroundVectorData>();

    public virtual Timeline Timeline { get; set; }
}