// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AIStoryBuilders.Models;

public partial class CharacterBackgroundParagraph
{
    public int Id { get; set; }

    public int Sequence { get; set; }

    public string Type { get; set; }

    public string Description { get; set; }

    public string ParagraphContent { get; set; }

    public virtual ICollection<CharacterBackgroundParagraphVectorData> CharacterBackgroundParagraphVectorData { get; set; } = new List<CharacterBackgroundParagraphVectorData>();

    public virtual ICollection<CharacterCharacterBackgroundParagraph> CharacterCharacterBackgroundParagraph { get; set; } = new List<CharacterCharacterBackgroundParagraph>();
}