// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AIStoryBuilders.Models;

public partial class Paragraph
{
    public int Id { get; set; }

    public int ChapterId { get; set; }

    public int Sequence { get; set; }

    public string Type { get; set; }

    public string Description { get; set; }

    public string ParagraphContent { get; set; }

    public int? TimelineId { get; set; }

    public virtual Chapter Chapter { get; set; }

    public virtual ICollection<ParagraphCharacter> ParagraphCharacter { get; set; } = new List<ParagraphCharacter>();

    public virtual ICollection<ParagraphLocation> ParagraphLocation { get; set; } = new List<ParagraphLocation>();

    public virtual ICollection<ParagraphVectorData> ParagraphVectorData { get; set; } = new List<ParagraphVectorData>();

    public virtual Timeline Timeline { get; set; }
}